Repository edgargavioli/telegram-chat-bot, pull requests merged in 2024-11, with the labels that each got.

#4 feat: controllers básicos
  .env
  api/controllers/categories_controller.py
  api/controllers/clients_controller.py
  api/controllers/orders_controller.py
  api/controllers/orders_items_controller.py
  api/controllers/products_controller.py
  api/controllers/user_controller.py
  api/models/products.py
  api/models/users.py
  app/__init__.py
  app/config.py
  app/routes/categorias.py
  app/routes/clientes.py
  app/routes/home.py
  app/routes/login.py
  app/routes/mensagens.py
  app/routes/pedidos.py
  app/routes/produtos.py
  app/routes/transmitir.py
  app/routes/usuarios.py
  app/static/css/style.css
  app/templates/base.html
  app/templates/index.html
  app/templates/pages/login.html
  migrations/versions/ed49013a0695_altera_o_tamanho_da_senha_do_usuário.py
  requirements.txt
Labels: feature

#5 feat: crud categorias
  api/controllers/categories_controller.py
  app/routes/categorias.py
  app/static/css/style.css
  app/static/img/editar.png
  app/static/img/excluir.png
  app/static/js/categorias.js
  app/templates/pages/categorias.html
  app/templates/pages/categorias/adicionar_categoria.html
  app/templates/pages/categorias/categorias.html
  app/templates/pages/categorias/editar_categoria.html
Labels: feature

#7 feat: crud produtos
  api/controllers/categories_controller.py
  api/controllers/products_controller.py
  app/config.py
  app/routes/categorias.py
  app/routes/produtos.py
  app/static/css/style.css
  app/static/js/categorias/categorias.js
  app/static/js/produtos/adicionarProduto.js
  app/static/js/produtos/editarProduto.js
  app/static/js/produtos/produtos.js
  app/templates/pages/categorias/adicionar_categoria.html
  app/templates/pages/categorias/categorias.html
  app/templates/pages/categorias/editar_categoria.html
  app/templates/pages/produtos.html
  app/templates/pages/produtos/adicionar_produto.html
  app/templates/pages/produtos/editar_produto.html
  app/templates/pages/produtos/produtos.html
Labels: feature

#12 feat: adiciona estilos de fonte e altera os icones
  app/static/css/style.css
  app/static/img/icons/category.svg
  app/static/img/icons/clients.svg
  app/static/img/icons/menu-close.svg
  app/static/img/icons/menu-open.svg
  app/static/img/icons/message.svg
  app/static/img/icons/orders.svg
  app/static/img/icons/product.svg
  app/static/img/icons/trasmite.svg
  app/static/img/icons/user.svg
  app/static/img/icons/users.svg
  app/static/js/script.js
  app/templates/base.html
  requirements.txt
Labels: feature

#13 Feat/orders
  api/controllers/orders_controller.py
  app/routes/pedidos.py
  app/static/img/produtos/Captura_de_tela_2024-10-28_212729.png
  app/static/js/pedidos/adicionarPedido.js
  app/static/js/pedidos/editarPedido.js
  app/static/js/pedidos/pedidos.js
  app/templates/pages/pedidos.html
  app/templates/pages/pedidos/adicionar_pedido.html
  app/templates/pages/pedidos/editar_pedido.html
  app/templates/pages/pedidos/pedidos.html
Labels: feature

#15 feat: crud usuários
  api/controllers/clients_controller.py
  api/controllers/user_controller.py
  api/models/clients.py
  api/models/users.py
  app/routes/clientes.py
  app/routes/usuarios.py
  app/static/css/style.css
  app/static/img/broadcast.png
  app/static/img/caixa.png
  app/static/img/carrinho.png
  app/static/img/detetive.png
  app/static/img/envelope.png
  app/static/img/pasta.png
  app/static/img/pessoas.png
  app/static/img/produtos/Captura_de_tela_2024-10-28_212729.png
  app/static/img/produtos/Tux.svg.png
  app/static/img/profile.png
  app/static/js/clientes/adicionar_cliente.js
  app/static/js/clientes/clientes.js
  app/static/js/clientes/editar_cliente.js
  app/static/js/clientes/editar_clientes.js
  app/static/js/pedidos/adicionarPedido.js
  app/static/js/pedidos/editarPedido.js
  app/static/js/produtos/adicionarProduto.js
  app/static/js/produtos/editarProduto.js
  app/static/js/usuarios/usuarios.js
  app/templates/base.html
  app/templates/pages/clientes.html
  app/templates/pages/clientes/adicionar_cliente.html
  app/templates/pages/clientes/clientes.html
  app/templates/pages/clientes/editar_cliente.html
  app/templates/pages/home.html
  app/templates/pages/pedidos/editar_pedido.html
  app/templates/pages/produtos/adicionar_produto.html
  app/templates/pages/usuarios.html
  app/templates/pages/usuarios/adicionar_usuario.html
  app/templates/pages/usuarios/editar_usuario.html
  app/templates/pages/usuarios/usuarios.html
  init.sql
Labels: feature

#17 Feat/mensageria
  api/controllers/clients_controller.py
  api/controllers/messages_controller.py
  api/models/clients.py
  app/__init__.py
  app/routes/mensagens.py
  app/static/css/style.css
  app/static/js/mensagens/mensagens.js
  app/templates/pages/mensagens.html
  app/templates/pages/mensagens/mensagens.html
  bot/commands/client.py
  bot/main.py
Labels: feature

#18 feat: adiciona a função de transmitir
  .env.example
  app/static/css/style.css
  app/static/js/mensagens/mensagens.js
  app/templates/base.html
  app/templates/pages/mensagens/mensagens.html
Labels: feature

#21 Fix: adiciona socker.io aos requirements
  requirements.txt
Labels: bug

#23 muda chat_id de int pra big int
  api/models/clients.py
Labels: bug

#24 feat: adiciona a persistencia das mensagens
  api/controllers/messages_controller.py
  api/models/clients.py
  api/models/messages.py
  app/__init__.py
  app/static/js/mensagens/mensagens.js
  bot/commands/human.py
  bot/main.py
Labels: feature

#26 feat: kanban
  api/controllers/orders_controller.py
  app/routes/home.py
  app/static/css/style.css
  app/static/img/produtos/IMG_20240726_161257.jpg
  app/static/js/home/home.js
  app/static/js/pedidos/pedidos.js
  app/templates/pages/home.html
  app/templates/pages/home/home.html
  app/templates/pages/pedidos/editar_pedido.html
Labels: feature

#29 feat: adiciona o envio de mensagem após a atulização de status
  api/controllers/messages_controller.py
  app/static/js/home/home.js
Labels: feature

#22 feat: arruma projeto pra rodar no docker e adiciona botão de remover …
  bot/commands/catalog.py
  bot/commands/send_backend_message.py
  bot/config.py
  bot/wait-for-it.sh
  docker-compose.yml
Labels: enhancement
